version: '3.9'

services:
  rusty-slack-traefik:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    volumes:
      - .:/usr/src/rusty-slack
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rusty-slack-traefik.entrypoints=web, websecure"
      - "traefik.http.routers.rusty-slack-traefik.rule=Host(`${MY_HOST}`)"
      - "traefik.http.routers.rusty-slack-traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.rusty-slack-traefik.tls.domains[0].main=${MY_HOST}"
      - "traefik.http.services.rusty-slack-traefik.loadbalancer.server.port=3000"
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${MY_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/shared/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/rurun/docker.sock:/var/run/docker.sock:ro"
      - "./sharen/docker.sock:/var/run/docker.sock:ro"
      - "./shared:/shared"
